Started by user [8mha:AAAAlh+LCAAAAAAAAABb85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAzOEgYu/dLi1CL9vNKcHACFIKlWvwAAAA==[0manonymous
Building in workspace /var/lib/jenkins/jobs/CloudCafeTest/workspace
Checkout:workspace / /var/lib/jenkins/jobs/CloudCafeTest/workspace - hudson.remoting.LocalChannel@6788af79
Using strategy: Default
Last Built Revision: Revision f06f5682a1a34bc5df0e159db85005270d02163c (remotes/origin/new_regression_run)
Fetching changes from 1 remote Git repository
Fetching upstream changes from origin
Commencing build of Revision f06f5682a1a34bc5df0e159db85005270d02163c (remotes/origin/new_regression_run)
Checking out Revision f06f5682a1a34bc5df0e159db85005270d02163c (remotes/origin/new_regression_run)
[workspace] $ /bin/bash /tmp/hudson1050483746846058103.sh
**> virtualenv exists
test_health_check_after_installation (testrepo.tq_search.test_health_check.TestHealthCheck)
B-41831::Testing the health after deployment ... ok
test_info_check_after_installation (testrepo.tq_search.test_health_check.TestHealthCheck)
B-41831::Testing the info after deployment ... ok
test_ticket_created_in_core_reflects_in_one_minute_in_tqsearch (testrepo.tq_search.core_ongoing_sync.test_core_ongoing_sync.TestCoreOngoingSync) ... FAIL
test_ticket_updated_in_core_reflects_in_one_minute_in_tqsearch (testrepo.tq_search.core_ongoing_sync.test_core_ongoing_sync.TestCoreOngoingSync) ... ERROR
test_updating_priority_in_core_marks_ticket_as_updated_in_search (testrepo.tq_search.core_ongoing_sync.test_core_ongoing_sync.TestCoreOngoingSync) ... ERROR
test_updating_queue_in_core_marks_ticket_as_updated_in_tq_search (testrepo.tq_search.core_ongoing_sync.test_core_ongoing_sync.TestCoreOngoingSync) ... ERROR
test_updating_status_in_core_marks_ticket_as_updated_in_search (testrepo.tq_search.core_ongoing_sync.test_core_ongoing_sync.TestCoreOngoingSync) ... ERROR
test_ascending_sorting_order_when_fetching_the_tickets (testrepo.tq_search.search_existing_ticket.test_pagination.TestPagination) ... ok
test_default_sorting_order_is_ascending (testrepo.tq_search.search_existing_ticket.test_pagination.TestPagination) ... ok
test_descending_sorting_order_when_fetching_the_tickets (testrepo.tq_search.search_existing_ticket.test_pagination.TestPagination) ... ok
test_first_link_of_pagination_during_list_ticket (testrepo.tq_search.search_existing_ticket.test_pagination.TestPagination) ... ok
test_last_link_of_pagination_during_list_ticket (testrepo.tq_search.search_existing_ticket.test_pagination.TestPagination) ... ok
test_next_previous_link_of_pagination_during_list_tickets (testrepo.tq_search.search_existing_ticket.test_pagination.TestPagination) ... ok
test_all_the_dates_are_converted_to_UTC_format (testrepo.tq_search.search_existing_ticket.test_fetch_existing_core_tickets.TestFetchExistingCoreTickets) ... ok
test_content_type_of_response (testrepo.tq_search.search_existing_ticket.test_fetch_existing_core_tickets.TestFetchExistingCoreTickets) ... ok
test_load_existing_tickets_to_ticket_search (testrepo.tq_search.search_existing_ticket.test_fetch_existing_core_tickets.TestFetchExistingCoreTickets) ... ok
test_list_tickets_and_verify_the_account_data (testrepo.tq_search.search_existing_ticket.test_account_information.TestAccountInformation) ... FAIL
test_same_number_of_accounts_in_account_svs_and_elastic_search (testrepo.tq_search.search_existing_ticket.test_account_information.TestAccountInformation) ... FAIL
test_update_ticket_attributes_and_verify_the_account_data (testrepo.tq_search.search_existing_ticket.test_account_information.TestAccountInformation) ... FAIL
test_get_specific_ticket_and_verify_it_exists_in_the_list (testrepo.tq_search.search_existing_ticket.test_list_tickets.TestListTickets) ... ERROR
test_get_specific_ticket_using_query_parameters (testrepo.tq_search.search_existing_ticket.test_list_tickets.TestListTickets) ... ok
test_list_tickets_by_date_range_in_query_params_with_eql_op (testrepo.tq_search.search_existing_ticket.test_list_tickets.TestListTickets) ... ERROR
test_list_tickets_by_date_range_in_query_params_with_not_eql_op (testrepo.tq_search.search_existing_ticket.test_list_tickets.TestListTickets) ... ok
test_list_tickets_by_multiple_values_for_equal_operator (testrepo.tq_search.search_existing_ticket.test_list_tickets.TestListTickets) ... ERROR
test_list_tickets_by_single_value_for_equal_operator (testrepo.tq_search.search_existing_ticket.test_list_tickets.TestListTickets) ... FAIL
test_list_tickets_eql_and_not_eql_op_single_val_in_query_params (testrepo.tq_search.search_existing_ticket.test_list_tickets.TestListTickets) ... ERROR
test_list_tickets_eql_and_noteql_op_multiple_vals_in_query_parms (testrepo.tq_search.search_existing_ticket.test_list_tickets.TestListTickets) ... ok
test_list_tickets_query_params_with_multiple_vals_and_not_eql_op (testrepo.tq_search.search_existing_ticket.test_list_tickets.TestListTickets) ... ok
test_list_tickets_query_params_with_single_value_and_eql_op (testrepo.tq_search.search_existing_ticket.test_list_tickets.TestListTickets) ... ok
test_list_tickets_query_params_with_single_value_and_not_eql_op (testrepo.tq_search.search_existing_ticket.test_list_tickets.TestListTickets) ... ok

======================================================================
ERROR: test_ticket_updated_in_core_reflects_in_one_minute_in_tqsearch (testrepo.tq_search.core_ongoing_sync.test_core_ongoing_sync.TestCoreOngoingSync)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/jobs/CloudCafeTest/workspace/lib/testrepo/tq_search/core_ongoing_sync/test_core_ongoing_sync.py", line 104, in test_ticket_updated_in_core_reflects_in_one_minute_in_tqsearch
    initial_date = string_to_datetime(search_ticket.tickets[0].updatedAt)
IndexError: list index out of range

======================================================================
ERROR: test_updating_priority_in_core_marks_ticket_as_updated_in_search (testrepo.tq_search.core_ongoing_sync.test_core_ongoing_sync.TestCoreOngoingSync)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/jobs/CloudCafeTest/workspace/lib/testrepo/tq_search/core_ongoing_sync/test_core_ongoing_sync.py", line 189, in test_updating_priority_in_core_marks_ticket_as_updated_in_search
    initial_date = string_to_datetime(search_ticket.tickets[0].updatedAt)
IndexError: list index out of range

======================================================================
ERROR: test_updating_queue_in_core_marks_ticket_as_updated_in_tq_search (testrepo.tq_search.core_ongoing_sync.test_core_ongoing_sync.TestCoreOngoingSync)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/jobs/CloudCafeTest/workspace/lib/testrepo/tq_search/core_ongoing_sync/test_core_ongoing_sync.py", line 224, in test_updating_queue_in_core_marks_ticket_as_updated_in_tq_search
    initial_date = string_to_datetime(search_ticket.tickets[0].updatedAt)
IndexError: list index out of range

======================================================================
ERROR: test_updating_status_in_core_marks_ticket_as_updated_in_search (testrepo.tq_search.core_ongoing_sync.test_core_ongoing_sync.TestCoreOngoingSync)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/jobs/CloudCafeTest/workspace/lib/testrepo/tq_search/core_ongoing_sync/test_core_ongoing_sync.py", line 156, in test_updating_status_in_core_marks_ticket_as_updated_in_search
    initial_date = string_to_datetime(search_ticket.tickets[0].updatedAt)
IndexError: list index out of range

======================================================================
ERROR: test_get_specific_ticket_and_verify_it_exists_in_the_list (testrepo.tq_search.search_existing_ticket.test_list_tickets.TestListTickets)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/jobs/CloudCafeTest/workspace/lib/testrepo/tq_search/search_existing_ticket/test_list_tickets.py", line 358, in test_get_specific_ticket_and_verify_it_exists_in_the_list
    self.assertEquals(tq_search_ticket.tickets[0], core_ticket,
AttributeError: 'NoneType' object has no attribute 'tickets'

======================================================================
ERROR: test_list_tickets_by_date_range_in_query_params_with_eql_op (testrepo.tq_search.search_existing_ticket.test_list_tickets.TestListTickets)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/jobs/CloudCafeTest/workspace/lib/testrepo/tq_search/search_existing_ticket/test_list_tickets.py", line 298, in test_list_tickets_by_date_range_in_query_params_with_eql_op
    self.assertTrue((len(ticket_list_from_core) == len(results.tickets))
AttributeError: 'NoneType' object has no attribute 'tickets'

======================================================================
ERROR: test_list_tickets_by_multiple_values_for_equal_operator (testrepo.tq_search.search_existing_ticket.test_list_tickets.TestListTickets)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/jobs/CloudCafeTest/workspace/lib/testrepo/tq_search/search_existing_ticket/test_list_tickets.py", line 75, in test_list_tickets_by_multiple_values_for_equal_operator
    results.tickets.sort(key=lambda x: x.number, reverse=False)
AttributeError: 'NoneType' object has no attribute 'tickets'

======================================================================
ERROR: test_list_tickets_eql_and_not_eql_op_single_val_in_query_params (testrepo.tq_search.search_existing_ticket.test_list_tickets.TestListTickets)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/jobs/CloudCafeTest/workspace/lib/testrepo/tq_search/search_existing_ticket/test_list_tickets.py", line 224, in test_list_tickets_eql_and_not_eql_op_single_val_in_query_params
    results.tickets.sort(key=lambda x: x.number, reverse=False)
AttributeError: 'NoneType' object has no attribute 'tickets'

======================================================================
FAIL: test_ticket_created_in_core_reflects_in_one_minute_in_tqsearch (testrepo.tq_search.core_ongoing_sync.test_core_ongoing_sync.TestCoreOngoingSync)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/jobs/CloudCafeTest/workspace/lib/testrepo/tq_search/core_ongoing_sync/test_core_ongoing_sync.py", line 79, in test_ticket_created_in_core_reflects_in_one_minute_in_tqsearch
    "The ticket{%s} is not present in tq_search")
AssertionError: False is not True : The ticket{%s} is not present in tq_search

======================================================================
FAIL: test_list_tickets_and_verify_the_account_data (testrepo.tq_search.search_existing_ticket.test_account_information.TestAccountInformation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/jobs/CloudCafeTest/workspace/lib/testrepo/tq_search/search_existing_ticket/test_account_information.py", line 62, in test_list_tickets_and_verify_the_account_data
    account_info_from_acc_svs)
AssertionError: <AccountServices object> 
status = Active
name = Savills Plc
team = Team EM5
number = 896236
rcn = RCN-000-047-049
highProfile = False
updatedAt = None
type = MANAGED_HOSTING
 != <AccountServices object> 
userName = UNDEFINED
status = Active
hybridNetworking = false
name = Savills Plc
region = US
team = Team UK M13
salesForceSubType = External Customer
number = 896236
slaType = NONE
rcn = RCN-000-047-049
highProfile = False
accountManagerGeoLocation = GB
type = MANAGED_HOSTING


======================================================================
FAIL: test_same_number_of_accounts_in_account_svs_and_elastic_search (testrepo.tq_search.search_existing_ticket.test_account_information.TestAccountInformation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/jobs/CloudCafeTest/workspace/lib/testrepo/tq_search/search_existing_ticket/test_account_information.py", line 114, in test_same_number_of_accounts_in_account_svs_and_elastic_search
    search and account services")
AssertionError: '426608' != '484537' : The number of accounts are not same in elastic                           search and account services

======================================================================
FAIL: test_update_ticket_attributes_and_verify_the_account_data (testrepo.tq_search.search_existing_ticket.test_account_information.TestAccountInformation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/jobs/CloudCafeTest/workspace/lib/testrepo/tq_search/search_existing_ticket/test_account_information.py", line 94, in test_update_ticket_attributes_and_verify_the_account_data
    get_account_info_from_acc_svs)
AssertionError: <AccountServices object> 
status = Closed
name = Rackspace Blog Audit
number = 829213
rcn = RCN-659-428-402
updatedAt = 2013-07-19T15:58:42.693+0000
highProfile = False
team = Team CS2
type = MANAGED_HOSTING
 != <AccountServices object> 
userName = UNDEFINED
status = Closed
hybridNetworking = false
name = Rackspace Blog Audit
region = US
team = Team UK M24
salesForceSubType = Internal
number = 829213
slaType = STANDARD
rcn = RCN-659-428-402
highProfile = False
accountManagerGeoLocation = US
type = MANAGED_HOSTING


======================================================================
FAIL: test_list_tickets_by_single_value_for_equal_operator (testrepo.tq_search.search_existing_ticket.test_list_tickets.TestListTickets)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/jobs/CloudCafeTest/workspace/lib/testrepo/tq_search/search_existing_ticket/test_list_tickets.py", line 49, in test_list_tickets_by_single_value_for_equal_operator
    len(results.tickets)))
AssertionError: False is not True : The length of two lists does not match. 4 != 3

----------------------------------------------------------------------
Ran 30 tests in 268.336s

FAILED (failures=5, errors=8)
======================================================================================================================================================
Log File Path: /var/lib/jenkins/jobs/CloudCafeTest/workspace/.cloudcafe/logs/tq_search/local.search.config/2013-07-24_14_52_08.938304
======================================================================================================================================================
426608
484537
Build step 'Execute shell' marked build as failure
Archiving artifacts
[htmlpublisher] Archiving HTML reports...
[htmlpublisher] Archiving at BUILD level /var/lib/jenkins/jobs/CloudCafeTest/workspace to /var/lib/jenkins/jobs/CloudCafeTest/builds/2013-07-24_14-52-06/htmlreports/HTML_Report
Finished: FAILURE
